#!/usr/bin/env python3
"""Generate the paper's results table and main figure from summary.csv.

This is the *only* place numbers in the paper come from. Re-running it
after a new sweep updates the LaTeX table and the figure together so
the manuscript can never drift from the data.

Usage:
    python scripts/build_paper_assets.py
"""
from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # headless
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
SUMMARY = ROOT / "results" / "summary.csv"
TABLE_OUT = ROOT / "paper" / "arxiv" / "results_table.tex"
FIG_OUT = ROOT / "paper" / "arxiv" / "figures" / "sample_efficiency.pdf"

METHOD_ORDER = ["scratch", "coco_transfer", "crosspoll", "crosspoll_freeze10"]
METHOD_LABEL = {
    "scratch": "Scratch",
    "coco_transfer": "COCO transfer",
    "crosspoll": "CrossPoll (full FT)",
    "crosspoll_freeze10": "CrossPoll + freeze",
}
METHOD_STYLE = {
    "scratch": dict(color="#888888", marker="x", linestyle=":"),
    "coco_transfer": dict(color="#1f77b4", marker="o", linestyle="-"),
    "crosspoll": dict(color="#d62728", marker="s", linestyle="--"),
    "crosspoll_freeze10": dict(color="#2ca02c", marker="^", linestyle="-"),
}
BUDGETS = [10, 25, 50, 100, 181]


def load_aggregated() -> dict[tuple[str, int], dict]:
    """Return {(method, budget): {n, m50_mean, m50_min, m50_max, m5095_mean}}."""
    raw = defaultdict(list)
    with open(SUMMARY) as f:
        for r in csv.DictReader(f):
            try:
                m50 = float(r["mAP50"])
            except (ValueError, KeyError):
                continue
            m5095 = None
            v = r.get("mAP50_95", "").strip()
            if v:
                try:
                    m5095 = float(v)
                    if m5095 == 0.0:  # empty cells were filled as 0 in some rows; ignore
                        m5095 = None
                except ValueError:
                    pass
            raw[(r["method"], int(r["n_labels"]))].append((m50, m5095))

    agg: dict[tuple[str, int], dict] = {}
    for key, vals in raw.items():
        m50s = [v[0] for v in vals]
        m5095s = [v[1] for v in vals if v[1] is not None]
        agg[key] = {
            "n": len(vals),
            "m50_mean": sum(m50s) / len(m50s),
            "m50_min": min(m50s),
            "m50_max": max(m50s),
            "m5095_mean": (sum(m5095s) / len(m5095s)) if m5095s else None,
            "m5095_n": len(m5095s),
        }
    return agg


def write_table(agg: dict) -> None:
    """LaTeX results table: methods × budgets, mean mAP50 (range)."""
    lines: list[str] = []
    lines.append("% Auto-generated by scripts/build_paper_assets.py — do not edit by hand.")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Held-out kiwi test mAP@0.5 by method and label budget. "
                 "Each cell is the mean over three seeds (42, 43, 44); "
                 "the bracketed range is [min, max]. "
                 "Bold marks the best mean per column.}")
    lines.append("\\label{tab:main-results}")
    lines.append("\\resizebox{\\linewidth}{!}{%")
    lines.append("\\begin{tabular}{lrrrrr}")
    lines.append("\\toprule")
    header = "Method & " + " & ".join(f"$n{{=}}{b}$" for b in BUDGETS) + " \\\\"
    lines.append(header)
    lines.append("\\midrule")

    # Find best per column
    best_per_b: dict[int, tuple[str, float]] = {}
    for b in BUDGETS:
        best = max(
            ((m, agg[(m, b)]["m50_mean"]) for m in METHOD_ORDER if (m, b) in agg),
            key=lambda x: x[1],
            default=None,
        )
        if best:
            best_per_b[b] = best

    for m in METHOD_ORDER:
        cells = [METHOD_LABEL[m]]
        for b in BUDGETS:
            if (m, b) not in agg:
                cells.append("--")
                continue
            stats = agg[(m, b)]
            mean_str = f"{stats['m50_mean']:.3f}"
            range_str = f"[{stats['m50_min']:.3f},\\,{stats['m50_max']:.3f}]"
            is_best = best_per_b.get(b) and best_per_b[b][0] == m
            entry = f"\\textbf{{{mean_str}}}" if is_best else mean_str
            cells.append(f"{entry}~{range_str}")
        lines.append(" & ".join(cells) + " \\\\")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}%")
    lines.append("}")
    lines.append("\\end{table}")

    TABLE_OUT.parent.mkdir(parents=True, exist_ok=True)
    TABLE_OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {TABLE_OUT.relative_to(ROOT)}")


def write_figure(agg: dict) -> None:
    """Sample-efficiency curves: mAP@0.5 vs label budget, log x."""
    fig, ax = plt.subplots(figsize=(5.6, 3.6))
    for m in METHOD_ORDER:
        xs = [b for b in BUDGETS if (m, b) in agg]
        means = [agg[(m, b)]["m50_mean"] for b in xs]
        # Asymmetric error bars: distance from mean to min/max
        err_lo = [agg[(m, b)]["m50_mean"] - agg[(m, b)]["m50_min"] for b in xs]
        err_hi = [agg[(m, b)]["m50_max"] - agg[(m, b)]["m50_mean"] for b in xs]
        ax.errorbar(
            xs, means, yerr=[err_lo, err_hi],
            label=METHOD_LABEL[m],
            capsize=2.5, markersize=5.5, linewidth=1.4,
            **METHOD_STYLE[m],
        )

    ax.set_xscale("log")
    ax.set_xticks(BUDGETS)
    ax.set_xticklabels([str(b) for b in BUDGETS])
    ax.set_xlabel("Kiwi training labels (n)")
    ax.set_ylabel("Test mAP@0.5")
    ax.set_ylim(-0.02, 1.0)
    ax.grid(True, which="both", alpha=0.25)
    ax.legend(loc="lower right", frameon=False, fontsize=9)
    fig.tight_layout()

    FIG_OUT.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(FIG_OUT)
    plt.close(fig)
    print(f"Wrote {FIG_OUT.relative_to(ROOT)}")


def print_summary(agg: dict) -> None:
    """Console sanity check — what numbers will appear in the paper."""
    print("\nNumbers that will appear in the paper:")
    print(f"  {'method':22s} {'budget':>6} {'mAP50':>9} {'range':>20} {'mAP50-95':>9}")
    for m in METHOD_ORDER:
        for b in BUDGETS:
            if (m, b) not in agg:
                continue
            s = agg[(m, b)]
            rng = f"[{s['m50_min']:.3f},{s['m50_max']:.3f}]"
            m5095 = f"{s['m5095_mean']:.3f}" if s["m5095_mean"] is not None else "n/a"
            print(f"  {m:22s} {b:>6d} {s['m50_mean']:>9.4f} {rng:>20} {m5095:>9}")


def main() -> None:
    agg = load_aggregated()
    write_table(agg)
    write_figure(agg)
    print_summary(agg)


if __name__ == "__main__":
    main()
